name: SampleStaticLibraryA
sln_path: Project/windows/SampleStaticLibraryA.sln
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryA_${PLATFORM}_${CONFIGURATION}.lib
